@host = localhost:3000

# GET  http://{{host}}/khuvuc
# GET  http://{{host}}/chinhanh

//--------------------------------------------------------------

# POST http://{{host}}/addKhuVuc
# content-type: application/x-www-form-urlencoded

# tenkhuvuc=Test 
# &
# motakhuvuc=Test

# POST http://{{host}}/addChiNhanh
# content-type: application/x-www-form-urlencoded

# idkhuvuc=Test 
# &
# ten=Test
# &
# diachi=Test
# &
# sdt=Test
# &
# mota=Test


//----------------------------------------------------------

# POST http://{{host}}/deleteChiNhanh
# content-type: application/x-www-form-urlencoded

# idChiNhanh=Test 